// <auto-generated />
namespace WeirdChess.Enums
{
    /// <summary>
    /// Enumeration for the types of the different IGameScreen objects
    /// </summary>
    public enum GameScreenType
    {
        Intro,
        GameMenu,
        Settings,
    }
}
