// <auto-generated />
namespace WeirdChess.Enums
{
    /// <summary>
    /// Enumeration for the different types of settings
    /// </summary>
    public enum SettingType
    {
        ScreenResolution,
        Music,
        Sound,
        MusicVolume,
        SoundVolume,
    }
}
