// <auto-generated />
namespace WeirdChess.Exceptions
{
    using System;
    
    /// <summary>
    /// Exception for DrawableComponent objects. Extends System ArgumentException
    /// </summary>
    public class DrawableComponentException : ArgumentException
    {
        /// <summary>
        /// Constructor that takes a string message as argument
        /// </summary>
        /// <param name="message">The error message to be passed to the base class</param>
        public DrawableComponentException(string message)
            : base(message)
        {
        }
    }
}
