// <auto-generated />
namespace WeirdChess.Exceptions
{
    using System;
    /// <summary>
    /// Exception class for GameScreenType enumeration.
    /// </summary>
    public class GameScreenTypeException : ArgumentOutOfRangeException
    {
        /// <summary>
        /// Exception construtor. Takes two arguments, which are then passed to the base constructor.
        /// </summary>
        /// <param name="paramName">The param name</param>
        /// <param name="message">The outer exception message</param>
        public GameScreenTypeException(string paramName, string message)
            : base(paramName, message)
        {
        }
    }
}
