// <auto-generated />
namespace WeirdChess.Exceptions
{
    using System;
    /// <summary>
    /// Exception for Invalid values for ISetting objects. Extends ArgumentOutOfRangeException
    /// </summary>
    public class InvalidSettingValueException : ArgumentOutOfRangeException
    {
        /// <summary>
        /// Constructor which takes two argumens and passes them to the base class.
        /// </summary>
        /// <param name="paramName">The name of the invalid parameter.</param>
        /// <param name="message">The error message associated with the error context.</param>
        public InvalidSettingValueException(string paramName, string message)
            : base(paramName, message)
        {
        }
    }
}
