// <auto-generated />
namespace UnitTests.IteratorTestCases
{
    using System;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using WeirdChess.Interfaces;

    [TestClass]
    public abstract class AbstractIteratorTestCase
    {
        private readonly string ValueA = "A";
        private readonly string ValueB = "B";
        private readonly string ValueC = "C";
        private readonly string ValueD = "D";
        private readonly int ValueOne = 1;
        private readonly int ValueTwo = 2;
        private readonly int ValueThree = 3;
        private readonly int ValueFour = 4;
        private string[] StringArray;
        private int[] IntArray;
        private IIterator<string> StringIterator;
        private IIterator<int> IntIterator;

        [ClassInitialize]
        public static void BaseInit(TestContext context)
        {
        }

        public abstract IIterator<string> GetStringIterator();
        public abstract IIterator<int> GetIntIterator();

    }
}
