// <auto-generated />
namespace WeirdChess.Interfaces
{
    /// <summary>
    /// Interface for Component objects
    /// </summary>
    public interface IComponent
    {
        /// <summary>
        /// Method for initializing the Component object.
        /// </summary>
        void Initilize();
        /// <summary>
        /// Method for update notification.
        /// </summary>
        void Update();
    }
}
