// <auto-generated/>
namespace WeirdChess.Interfaces
{
    /// <summary>
    /// Interface for Deserialiser objects
    /// </summary>
    /// <typeparam name="T">Specifies the return type of the Deserialise method. 
    /// Can only be an object, which implments ISavable</typeparam>
    public interface IDeserialiser<out T> where T : ISavable
    {
        /// <summary>
        /// When called, reads the file, 
        /// specified by the FilePath property and returns the information from it, as a new ISavable object.
        /// </summary>
        /// <param name="filePath">The path to the target file</param>
        /// <returns>A new ISavable object, containing the deserialised information.</returns>
        T Deserialize(string filePath);
    }
}
