// <auto-generated/>
namespace WeirdChess.Interfaces
{
    /// <summary>
    /// Interface for Deserialiser objects
    /// </summary>
    /// <typeparam name="T">Specifies the return type of the Deserialise method. 
    /// Can only be an object, which implments ISavable</typeparam>
    public interface IDeserializer<out T> where T : ISavable
    {
        /// <summary>
        /// The target file path specified within the object constructor.
        /// The target file will be read and the information from it - returned as a new ISavable object.
        /// </summary>
        string FilePath { get; }
        /// <summary>
        /// When called, reads the file, 
        /// specified by the FilePath property and returns the information from it, as a new ISavable object.
        /// </summary>
        /// <returns>A new ISavable object, containing the deserialised information.</returns>
        T Deserialize();
    }
}
