// <auto-generated />
namespace WeirdChess.Interfaces
{
    /// <summary>
    /// Interface for Drawable Components
    /// </summary>
    public interface IDrawableComponent
    {
        /// <summary>
        /// Property which holds the Drawable Component of the Component object
        /// </summary>
        IDrawable DrawableComponent { get; }
    }
}
