// <auto-generated />
namespace WeirdChess.Interfaces
{
    /// <summary>
    /// Interface for Drawable objects
    /// </summary>
    public interface IDrawable
    {
        /// <summary>
        /// Method for drawing notification
        /// </summary>
        void Draw();
    }
}
