// <auto-generated />
namespace WeirdChess.Interfaces
{
    using Enums;
    /// <summary>
    /// Interface for GameScreen objects
    /// </summary>
    public interface IGameScreen
    {
        /// <summary>
        /// The Type of the current GameScreen object.
        /// </summary>
        GameScreenType Type { get; }
        /// <summary>
        /// Specifies if the current GameScreen object is on focus.
        /// True if the current screen is on focus.
        /// False if the curent screen is not on focus.
        /// </summary>
        bool Displayed { get; set; }
    }
}
