// <auto-generated />
namespace WeirdChess.Interfaces
{
    /// <summary>
    /// Interface for iterable objects.
    /// </summary>
    /// <typeparam name="T">The type of objects that the iterator will iterate through</typeparam>
    public interface IIterable<out T>
    {
        /// <summary>
        /// Method for retreiving an iterator of generic type T
        /// </summary>
        /// <returns>An iterator for navigating between objects of generic type T</returns>
        IIterator<T> GetIterator();
    }
}
