// <auto-generated/>
namespace WeirdChess.Interfaces
{
    /// <summary>
    /// Interface for objects, which can be read and saved to a file.
    /// Contains methods for parsing objects to different types.
    /// </summary>
    public interface ISavable
    {
        /// <summary>
        /// Checks if the current object implements the ISettings interface.
        /// </summary>
        /// <returns>True if the object implements ISettings</returns>
        bool IsSetting();
        /// <summary>
        /// Attempts to cast the current object to an ISettings object.
        /// </summary>
        /// <returns></returns>
        ISettings AsSettings();
    }
}
