// <auto-generated />
namespace WeirdChess.Interfaces
{
    /// <summary>
    /// Interface for Serialisation Tool objects. 
    /// Contains a Serialiser and Deserialiser objects, created automatically upon initialisation.
    /// </summary>
    /// <typeparam name="T">An ISavable object, specifying the type of the ISerialiser and IDeserialiser objects</typeparam>
    public interface ISerialisationTool<T> where T : ISavable
    {
        /// <summary>
        /// Property containing an ISerialiser object of type T
        /// </summary>
        ISerialiser<T> Serialiser { get; }
        /// <summary>
        /// Property containing an IDeserialiser object of type T
        /// </summary>
        IDeserialiser<T> Deserialiser { get; } 
    }
}
