// <auto-generated />
namespace WeirdChess.Interfaces
{
    /// <summary>
    /// Interface for Serialiser objects.
    /// </summary>
    /// <typeparam name="T">Specifies the argument type of the object to be serialised.
    /// Can only be an object, which implements ISavable</typeparam>
    public interface ISerialiser<in T> where T : ISavable
    {
        /// <summary>
        /// Writes the information from the T object to to the file specified by the FilePath property.
        /// </summary>
        /// <param name="filePath">The path to the target file.</param>
        /// <param name="settings">An ISavable object which contains the information to be written to the file.</param>
        void Serialise(string filePath, T settings);
    }
}
