// <auto-generated />
namespace WeirdChess.Interfaces
{
    /// <summary>
    /// Interface for Serialisation Tool objects. 
    /// Contains a Serialise and Deserialise methods, created automatically upon initialisation.
    /// </summary>
    /// <typeparam name="T">An ISavable object, specifying the type of the ISerialiser and IDeserialiser objects</typeparam>
    public interface ISerialisationTool<T> where T : ISavable
    {
        /// <summary>
        /// The target file path specified within the object constructor.
        /// </summary>
        string FilePath { get; }
        /// <summary>
        /// Serialises the ISavable object from the argument into the file, specified in the FilePath property.
        /// </summary>
        /// <param name="savableObject">The ISavable object, containing the information that's to be serialised.</param>
        void Serialise(T savableObject);
        /// <summary>
        /// Deserialises the information from the file, specified in the FilePath property, into an ISavable object.
        /// </summary>
        /// <returns>The deserialised information, as an ISavable object</returns>
        T Deserialise();
    }
}
