// <auto-generated />
namespace WeirdChess.Interfaces
{
    /// <summary>
    /// Interface for Settings Controller objects
    /// </summary>
    public interface ISettingsController
    {
        /// <summary>
        /// Property containing the ISerialisationTool object, used for getting and saving settings.
        /// Specified in the object constructor.
        /// </summary>
        ISerialisationTool<ISavable> SerialisationTool { get; }
        /// <summary>
        /// Property containing the current settings.
        /// The value is default(ISettings) by default.
        /// When invoked, if the value is set, returns the current ISettings object.
        /// If not set, a new ISettings object is created through 
        /// the SerialisationTool, assigned to the property and returned as a result.
        /// If the source of the ISavable object does not exist, a new one is created with the default settings.
        /// </summary>
        ISettings Settings { get; }
        /// <summary>
        /// Saves the current ISettings object, using the SerialisationTool.
        /// </summary>
        void SaveSettings();
    }
}
