// <auto-generated/>
namespace WeirdChess.Interfaces
{
    using Enums;
    /// <summary>
    /// An interface for ISettings objects. Implments ISavable.
    /// </summary>
    public interface ISettings : ISavable
    {
        /// <summary>
        /// Contains the current screen resolution values as an int array.
        /// Screen width is on index 0.
        /// Screen height is on index 1.
        /// </summary>
        ISetting<int[]> ScreenResolution { get; }
        /// <summary>
        /// Property for the current music setting.
        /// </summary>
        ISetting<MusicOptions> Music { get; }
        /// <summary>
        /// Property for the current Sound setting.
        /// </summary>
        ISetting<SoundOptions> Sound { get; }
        /// <summary>
        /// Property for the current Music Volume setting.
        /// </summary>
        ISetting<int> MusicVolume { get; }
        /// <summary>
        /// Property for the current Sound Volume setting.
        /// </summary>
        ISetting<int> SoundVolume { get; } 
    }
}
