// <auto-generated/>
namespace WeirdChess.Interfaces
{
    using Enums;
    /// <summary>
    /// An interface for ISettings objects. Implments ISavable.
    /// </summary>
    public interface ISettings : ISavable
    {
        /// <summary>
        /// Method for retreiving the specified ISetting object.
        /// </summary>
        /// <param name="settingType">The setting type which is to be returned</param>
        /// <returns>An ISetting object, corresponding to the specified SettingType argument</returns>
        ISetting GetSetting(SettingType settingType);
        /// <summary>
        /// Method for setting values on ISetting objects. 
        /// </summary>
        /// <param name="settingType">The setting type whose value will be changed</param>
        /// <param name="value">The new value for the specified ISetting object</param>
        void SetSetting(SettingType settingType, object value);
    }
}
