// <auto-generated />
namespace WeirdChess.Interfaces
{
    using Enums;
    /// <summary>
    /// Interface for Settings Factory objects
    /// </summary>
    public interface ISettingFactory
    {
        /// <summary>
        /// Method for creating ISetting objects.
        /// </summary>
        /// <param name="settingType">The type of the new ISetting object.</param>
        /// <param name="settingValue">The value of the new ISetting object.</param>
        /// <returns>A new ISetting object, created with the method arguments.</returns>
        ISetting CreateSetting(SettingType settingType, object settingValue);
    }
}
