// <auto-generated/>
namespace WeirdChess.Interfaces
{
    using Enums;
    /// <summary>
    /// An interface for Setting objects
    /// </summary>
    public interface ISetting
    {
        /// <summary>
        /// The type of the setting object.
        /// </summary>
        SettingType Type { get; }
        /// <summary>
        /// The value of the setting object.
        /// </summary>
        object Value { get; }
    }
}
