
// <auto-generated />
namespace UnitTests.SettingTestCases
{
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using WeirdChess.Enums;
    using WeirdChess.Infrastructure;
    using WeirdChess.Interfaces;
    using WeirdChess.Utilities;

    [TestClass]
    public class MusicSettingTestCase : AbstractISettingTestCase
    {

        protected override ISetting GetSetting()
        {
            return new MusicSetting();
        }

        protected override ISetting GetSetting(object value)
        {
            return new MusicSetting((MusicOptions)value);
        }

        protected override SettingType GetSettingType()
        {
            return SettingType.Music;
        }

        protected override object GetDefaultValue()
        {
            return AllowedSettings.MusicOptionValues[0];
        }

        protected override object[] GetAllowedValues()
        {
            return new[] {AllowedSettings.MusicOptionValues};
        }

        protected override object[] GetInvalidValues()
        {
            return new[] {new[] {default(MusicOptions)}};
        }
    }
}
