// <auto-generated />
namespace UnitTests.SettingTestCases
{
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using WeirdChess.Enums;
    using WeirdChess.Interfaces;
    using WeirdChess.Infrastructure;
    using WeirdChess.Utilities;

    [TestClass]
    public class ScreenResolutionSettingTestCase : AbstractISettingTestCase
    {

        protected override ISetting GetSetting()
        {
            return new ScreenResolutionSetting();
        }

        protected override ISetting GetSetting(object value)
        {
            return new ScreenResolutionSetting(value.ToString());
        }

        protected override SettingType GetSettingType()
        {
            return SettingType.ScreenResolution;
        }

        protected override object GetDefaultValue()
        {
            return AllowedSettings.ScreenResolutionValues[0];
        }

        protected override object[] GetAllowedValues()
        {
            return AllowedSettings.ScreenResolutionValues;
        }

        protected override object[] GetInvalidValues()
        {
            return new[] {"1x1", "-1x-1", "300x190", "3000x3000"};
        }
    }
}
