// <auto-generated />
namespace WeirdChess.Utilities
{
    using Enums;
    /// <summary>
    /// Static class holding collections of allowed values for ISetting objects
    /// </summary>
    public static class AllowedSettings
    {
        /// <summary>
        /// Array of allowed Screen resolution values
        /// Name	Dimension (w x h)	Aspect Ratio	Pixels (*)	Comment
        // CGA 	    320 x 200 	16:10 	62.5 k 	Color Graphics Adapter - first display standard for PCs with color displays.
        // QVGA 	320 x 240 	4:3 	75.0 k 	Quarter VGA - Popular format for mobile devices.
        // VGA 	    640 x 480 	4:3 	300 k 	Video Graphics Array - Standard resolution for PC monitors in the 1990s, nowadays popular display resolution for PDAs.
        // SVGA 	800 x 600 	4:3 	469 k 	Super VGA - introduced by VESA group.
        // WVGA 	854 x 480 	16:9 	400 k 	Widescreen VGA - more or less unimportant format.
        // XGA 	    1024 x 768 	4:3 	768 k 	Extended Graphics Array
        // XGA+ 	1152 x 768 	3:2 	864 k 	XGA Plus
        // WXGA 	1280 x 800 	16:10 	1000 k 	Widescreen XGA (see also 1440 x 900)
        //  	    1280 x 854 	3:2 	1.04 M 	 
        // 	        1280 x 960 	4:3 	1.17 M 	 
        // SXGA 	1280 x 1024 5:4 	1.25 M 	Super XGA
        // SXGA+ 	1400 x 1050 4:3 	1.40 M 	Super XGA Plus
        // WXGA 	1440 x 900 	16:10 	1.24 M 	Widescreen XGA (see also 1280 x 800)
        //  	    1440 x 960 	3:2 	1.32 M 	 
        // UXGA 	1600 x 1200 4:3 	1.83 M 	Ultra XGA
        // WSXGA+ 	1680 x 1050 16:10 	1.68 M 	Widescreen Super XGA Plus
        // WUXGA 	1920 x 1200 16:10 	2.20 M 	Widescreen Ultra XGA
        // QXGA 	2048 x 1536 4:3 	3.00 M 	Quad XGA
        // WQXGA 	2560 x 1600 16:10 	3.91 M 	Widescreen Quad XGA
        // QSXGA 	2560 x 2048 5:4 	5.00 M 	Quad Super XGA
        /// </summary>
        public static readonly string[] ScreenResolutionValues = new string[]
        {
            "320x200",
            "320x240",
            "640x480",
            "800x600",
            "854x480",
            "1024x768",
            "1152x768",
            "1280x800",
            "1280x854",
            "1280x960",
            "1280x1024",
            "1400x1050",
            "1440x900",
            "1440x960",
            "1600x1200",
            "1680x1050 ",
            "1920x1200",
            "2048x1536",
            "2560x1600",
            "2560x2048",
        };
        /// <summary>
        /// Array of allowed MusicOption values.
        /// </summary>
        public static readonly MusicOptions[] MusicOptionValues =
        {
            MusicOptions.On, 
            MusicOptions.Off,
        };
        /// <summary>
        /// Array of allowed SoundOption values.
        /// </summary>
        public static readonly SoundOptions[] SoundOptionValues =
        {
            SoundOptions.On,
            SoundOptions.Off,
        };
        /// <summary>
        /// Array of allowed Music Volume values.
        /// </summary>
        public static readonly int[] MusicVolumeValues =
        {
            0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
            11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
            21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
            31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
            41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
            61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
            71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
            81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
            91, 92, 93, 94, 95, 96, 97, 98, 99, 100
        };
        /// <summary>
        /// Array of allowed Sound Volume values.
        /// </summary>
        public static readonly int[] SoundVolumeValues =
        {
            0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
            11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
            21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
            31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
            41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
            61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
            71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
            81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
            91, 92, 93, 94, 95, 96, 97, 98, 99, 100
        };
    }
}
