// <auto-generated />
namespace WeirdChess.Utilities
{
    /// <summary>
    /// Class containing constant messages
    /// </summary>
    public static class Messages
    {
        public const string DrawableObjectNotSet = "Drawable Object is not set for object {0}";
    }
}
